import fs from 'node:fs/promises';
import path from 'node:path';
import type { Finding, Layer, ScanResult, Severity } from '../types.js';

const LAYER_LABELS: Record<Layer, string> = {
  frontend: 'Frontend',
  backend: 'Backend & API',
  network: 'Network & Infrastructure',
  database: 'Database',
  cicd: 'CI/CD & DevOps',
  observability: 'Observability',
};

const LAYER_DESCRIPTIONS: Record<Layer, string> = {
  frontend: 'Client-side rendering, DOM manipulation, cookies, asset exposure',
  backend: 'API endpoints, authentication, input validation, file uploads',
  network: 'HTTP security headers, CORS, transport security',
  database: 'Privilege separation, encryption at rest and in transit',
  cicd: 'Dependency hygiene, secret management, build pipeline',
  observability: 'Error handling, log safety, anomaly detection',
};

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🟣',
  high: '🔴',
  medium: '🟠',
  low: '🟡',
  info: '🔵',
};

const SEVERITY_ORDER: Record<Severity, number> = {
  critical: 0,
  high: 1,
  medium: 2,
  low: 3,
  info: 4,
};

export async function writeSecurityReport(
  result: ScanResult,
  reportPath: string
): Promise<string> {
  const md = renderSecurityMarkdown(result);
  const absolute = path.resolve(reportPath);
  await fs.mkdir(path.dirname(absolute), { recursive: true });
  await fs.writeFile(absolute, md, 'utf8');
  return absolute;
}

export function renderSecurityMarkdown(result: ScanResult): string {
  const lines: string[] = [];
  const projectName = path.basename(result.rootDir);

  lines.push(`# Security Audit -- ${projectName}`);
  lines.push('');
  lines.push(
    `> Generated by **Vibe Security** on ${result.startedAt}. ` +
      `${result.summary.totalFindings} finding(s) across ${result.filesScanned} file(s) ` +
      `using ${result.rulesEvaluated} rule(s) in ${result.durationMs}ms.`
  );
  lines.push('');

  lines.push('## Executive Summary');
  lines.push('');
  lines.push('| Severity | Count |');
  lines.push('| --- | --- |');
  for (const sev of ['critical', 'high', 'medium', 'low', 'info'] as Severity[]) {
    lines.push(`| ${SEVERITY_EMOJI[sev]} ${capitalize(sev)} | ${result.summary.bySeverity[sev]} |`);
  }
  lines.push('');

  if (result.errors && result.errors.length > 0) {
    lines.push('## Scan Warnings');
    lines.push('');
    lines.push(`The scan completed with ${result.errors.length} error(s). Affected files or rules may not have been fully analyzed.`);
    lines.push('');
    for (const error of result.errors) {
      const location = [error.file, error.ruleId].filter(Boolean).join(' / ');
      lines.push(`- ${location ? `**${location}**: ` : ''}${error.message}`);
    }
    lines.push('');
  }

  if (result.summary.totalFindings === 0) {
    lines.push('**No security issues detected.** Maintain a healthy baseline by re-running this scan on every major change.');
    lines.push('');
    return lines.join('\n');
  }

  lines.push('## Findings by Layer');
  lines.push('');
  lines.push('| Layer | Description | Findings |');
  lines.push('| --- | --- | --- |');
  for (const layer of Object.keys(LAYER_LABELS) as Layer[]) {
    if (result.summary.byLayer[layer] === 0) continue;
    lines.push(
      `| **${LAYER_LABELS[layer]}** | ${LAYER_DESCRIPTIONS[layer]} | ${result.summary.byLayer[layer]} |`
    );
  }
  lines.push('');

  const byLayer = new Map<Layer, Finding[]>();
  for (const f of result.findings) {
    if (!byLayer.has(f.layer)) byLayer.set(f.layer, []);
    byLayer.get(f.layer)!.push(f);
  }

  for (const layer of Object.keys(LAYER_LABELS) as Layer[]) {
    const items = byLayer.get(layer);
    if (!items || items.length === 0) continue;

    lines.push(`## ${LAYER_LABELS[layer]}`);
    lines.push('');
    items.sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]);
    for (const f of items) {
      lines.push(renderFinding(f));
      lines.push('');
    }
  }

  lines.push('## How to fix');
  lines.push('');
  lines.push('1. Address **Critical** and **High** findings first.');
  lines.push('2. Apply remediations in the order suggested by each rule.');
  lines.push('3. Re-run `vibe-security scan_project` after each fix batch.');
  lines.push('4. Wire this scan into CI so regressions surface automatically.');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('Generated by [Vibe Security](https://github.com/korayda4/Vibe-Security) -- MCP server for AI Vibe Coders.');
  lines.push('');

  return lines.join('\n');
}

function renderFinding(f: Finding): string {
  const out: string[] = [];
  out.push(`### ${SEVERITY_EMOJI[f.severity]} ${f.title}`);
  out.push('');
  out.push(`- **Rule ID:** \`${f.ruleId}\``);
  out.push(`- **Severity:** ${capitalize(f.severity)}`);
  if (f.cwe) out.push(`- **CWE:** ${f.cwe}`);
  if (f.owasp) out.push(`- **OWASP:** ${f.owasp}`);
  out.push(`- **File:** \`${f.file}\` (line ${f.match.line})`);
  out.push('');
  out.push('**Description**');
  out.push('');
  out.push(f.description);
  out.push('');
  out.push('**Impact**');
  out.push('');
  out.push(f.impact);
  out.push('');
  out.push('**Snippet**');
  out.push('');
  out.push('```');
  out.push(f.match.snippet.trim() || '(empty)');
  out.push('```');
  out.push('');
  out.push('**Remediation**');
  out.push('');
  out.push(f.remediation);
  if (f.references.length > 0) {
    out.push('');
    out.push('**References**');
    out.push('');
    for (const ref of f.references) {
      out.push(`- ${ref}`);
    }
  }
  return out.join('\n');
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
